name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x86_64
            opt_level: avx512
          - os: ubuntu-24.04-arm
            arch: aarch64
            opt_level: sve
          - os: macos-13
            arch: x86_64
            opt_level: avx2
          - os: macos-14
            arch: arm64
            opt_level: generic
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Apply patch
        run: git apply --directory third-party/faiss/ patch/cmake_python_module.patch
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.4
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_ENVIRONMENT_LINUX: >
            SKBUILD_CMAKE_DEFINE="FAISS_OPT_LEVEL=${{ matrix.opt_level }}"
          CIBW_ENVIRONMENT_MACOS: >
            SKBUILD_CMAKE_DEFINE="FAISS_OPT_LEVEL=${{ matrix.opt_level }}"
            MACOSX_DEPLOYMENT_TARGET=${{ matrix.os == 'macos-13' && '10.13' || '10.14' }}
            OpenMP_ROOT=${{ matrix.os == 'macos-13' && '/usr/local/opt/libomp' || '/opt/homebrew/opt/libomp'}}
          CIBW_BEFORE_ALL: bash scripts/before_${{ runner.os }}.sh
      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl